### PR TITLE
geoip: implement `GeoIpDatabase` methods added in ES 8.14

### LINKED ISSUE #138: elastic_integration plugin build broken due to recent GeoIP change in ES.
### Description

`elastic_integration` plugin build and E2E (builds the plugin and runs E2E tests) BK pipelines ([build CI failure](https://buildkite.com/elastic/logstash-filter-elastic-integration-build/builds/162#018f06fa-eb5f-4247-8ac9-3237555a7514), [E2E CI failure](https://buildkite.com/elastic/logstash-filter-elastic-integration-build/builds/163#018f072d-aaf0-489c-aff1-4eff16d2533f)) are failing due to [recent GeoIP change](https://github.com/elastic/elasticsearch/pull/107377) in Elasticsearch.

```
612.3 /usr/share/plugins/plugin/src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/GeoIpDatabaseAdapter.java:26: error: GeoIpDatabaseAdapter is not abstract and does not override abstract method getEnterprise(InetAddress) in GeoIpDatabase
612.3 public class GeoIpDatabaseAdapter implements GeoIpDatabase, Closeable {
612.3        ^
```

### PR DESCRIPTION
**Pull request by yaauie**
Catches up with Elasticsearch 8.14+ support for user-provided databases:
 - `Anonymous-IP` elastic/elasticsearch#107287
 - `Enterprise` elastic/elasticsearch#107377

When compiled against Elasticsearch < 8.14, these methods neither exist in the interface nor are reachable by the GeoIP processor.

Resolves #138

### CODE REVIEW

File: src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/GeoIpDatabaseAdapter.java [hunk 1]
```diff
@@ -52,6 +54,16 @@ public AsnResponse getAsn(InetAddress inetAddress) {
         return getResponse(inetAddress, this.databaseReader::tryAsn);
     }
 
+    /* @Override // neither available nor reachable until Elasticsearch 8.14 */
```
Comment (yaauie) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/GeoIpDatabaseAdapter.java:57]: review note: _yes_ this annotation is commented out; it should be un-commented once we are exclusively building against Elasticsearch 8.14+.

Unfortunately, since these methods do not exist when compiling against Elasticsearch < 8.14, an `@Override` annotation would prevent compilation.

Since it is commented out, we do not have a compile-time guarantee that we are _overriding_ the method from the interface (as opposed to overloading it).

I could not think of a way to dynamically implement the upstream `GeoIpDatabase` without resorting to very complex reflection-based proxy dispatch.

**Review by mashhurs — APPROVED** [review]
LGTM!
