### PR TITLE
Move to ES bridge API

### LINKED ISSUE #331: [Move to ES bridge -> ES scope] Evaluate current status of Stable API based on plugin usage
## Description
After introducing Bridge API multiple plugin breaks happened and as I do see some extra dependencies were consumed. Or we never PoCed if Bridge wrappers actually work. This issue uses Bridge API as it is and listed all the gaps need to be addressed.
For the visibility, I have created a [draft PR](https://github.com/elastic/logstash-filter-elastic_integration/pull/336) which actually build with Bridge API and runs unit/integration test. Unfortunately due to ES [`main` change](https://github.com/elastic/elasticsearch/commit/b52c6f7f27a1ed802e99df617b7a6bb505060b58) the plugin build is broken but I have luckily capture just before this change.

## CRITICAL ISSUES
(_see the full investigation points below_)

For the painless plugin, we had a logic to apply extensions. This was executed through initializing the `ScriptService` and as we moved the `ScriptService` to the Bridge and simplified (include whitelists, etc..), we no longer need the `ScriptService` initialization in the plugin. However, it seems we still need to add the extensions in the bridge
- relative source in the Bridge API
```
// ScriptServiceBridge.java
public class ScriptServiceBridge extends StableBridgeAPI.Proxy<ScriptService> implements Closeable {
    public ScriptServiceBridge wrap(final ScriptService delegate) {
        return new ScriptServiceBridge(delegate);
    }

    public ScriptServiceBridge(final SettingsBridge settingsBridge, final LongSupplier timeProvider) {
        super(getScriptService(settingsBridge.unwrap(), timeProvider));
    }

    public ScriptServiceBridge(ScriptService delegate) {
        super(delegate);
    }

    private static ScriptService getScriptService(final Settings settings, final LongSupplier timeProvider) {
        final List<Whitelist> painlessBaseWhitelist = getPainlessBaseWhiteList();
        final Map<ScriptContext<?>, List<Whitelist>> scriptContexts = Map.of(
            IngestScript.CONTEXT,
            painlessBaseWhitelist,
            IngestConditionalScript.CONTEXT,
            painlessBaseWhitelist
        );
        final Map<String, ScriptEngine> scriptEngines = Map.of(
            PainlessScriptEngine.NAME,
            new PainlessScriptEngine(settings, scriptContexts),
            MustacheScriptEngine.NAME,
            new MustacheScriptEngine(settings)
        );
        return new ScriptService(settings, scriptEngines, ScriptModule.CORE_CONTEXTS, timeProvider);
    }

    private static List<Whitelist> getPainlessBaseWhiteList() {
        return PainlessPlugin.baseWhiteList();
    }

    @Override
    public void close() throws IOException {
        this.delegate.close();
    }
```

- relative source (can be removed) in the plugin
`src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java` file:
```
    private static ScriptService initScriptService(final Settings settings, final ThreadPool threadPool) throws IOException {
        Map<String, ScriptEngine> engines = new HashMap<>();
        engines.put(PainlessScriptEngine.NAME, getPainlessScriptEngine(settings));
        engines.put(MustacheScriptEngine.NAME, new MustacheScriptEngine(settings));
        return new ScriptService(settings, engines, ScriptModule.CORE_CONTEXTS, threadPool::absoluteTimeInMillis);
    }

    /**
     * @param settings the Elasticsearch settings object
     * @return a {@link ScriptEngine} for painless scripts for use in {@link IngestScript} and
     *         {@link IngestConditionalScript} contexts, including all available {@link PainlessExtension}s.
     * @throws IOException when the underlying script engine cannot be created
     */
    private static ScriptEngine getPainlessScriptEngine(final Settings settings) throws IOException {
        try (final PainlessPlugin painlessPlugin = new PainlessPlugin()) {

            painlessPlugin.loadExtensions(new ExtensiblePlugin.ExtensionLoader() {
                @Override
                @SuppressWarnings("unchecked")
                public <T> List<T> loadExtensions(Class<T> extensionPointType) {
                    if (extensionPointType.isAssignableFrom(PainlessExtension.class)) {
                        final List<PainlessExtension> extensions = new ArrayList<>();

                        extensions.add(new ConstantKeywordPainlessExtension()); // module: constant-keyword
                        extensions.add(new ProcessorsWhitelistExtension());     // module: ingest-common
                        extensions.add(new SpatialPainlessExtension());         // module: spatial
                        extensions.add(new WildcardPainlessExtension());        // module: wildcard

                        return (List<T>) extensions;
                    } else {
                        return List.of();
                    }
                }
            });

            return painlessPlugin.getScriptEngine(settings, Set.of(IngestScript.CONTEXT, IngestConditionalScript.CONTEXT));
        }
    }
```

## Investigation
- see the CRITICAL ISSUE above
- introduce module descriptors for the plugins which makes them available to the logstash-bridge
- `ProjectId`: it recently came into play (with https://github.com/elastic/logstash-filter-elastic_integration/pull/273) 
  - it seems we can safely remove this dependency as `null` was applied for it: https://github.com/elastic/elasticsearch/blob/main/libs/logstash-bridge/src/main/java/org/elasticsearch/logstashbridge/ingest/PipelineBridge.java#L37 ([the PR](https://github.com/elastic/elasticsearch/pull/124099))
  - however, for the long term apply `ProjectId.DEFAULT` instead `null`
- `org.elasticsearch.core.Releasable` (used by `IntegrationBatch.java`) dependency: it seems it was missed
- `org.elasticsearch.action.support.RefCountingRunnable` (used by `EventProcessor.java`) dependency: it seems it was missed
- `org.elasticsearch.ingest.common.FailProcessorException` dependency: it seems it was missed
- removed `org.elasticsearch.core.Strings.format` dependency and the same logic behind `org.elasticsearch.core.Strings.format` can be simply applied with `String.format(Locale.ROOT, args)`
- `IngestDocument.Metadata.VERSION` was referenced in the plugin but we do not have a wrapper in the bridge for this enum
- Processors:
  - all processors are directly consumed in the plugins, we need to move them to the ES or do they stay? - My concern is plugin behaviour (particular processor support or not) should be controlled by the plugin not by ES imho.
  - `RedactProcessor` with its license (`XPackLicenseState`) dependant is not covered
  - `SetSecurityUserProcessor` can be removed, the PR - https://github.com/elastic/logstash-filter-elastic_integration/pull/269

### PR DESCRIPTION
**Pull request by mashhurs**
## Description
This PR highlights the _initial_ changes required to move to the Bridge Stable API. However, this doesn't mean these changes will be enough for the plugin to be a in normal working state. Rather, this changes _highlight_ how does current bridge Spable API state align with plugin requirements. Based on the discussions on these changes, we may need to adjust the plan (sub-tasks). 

- Closes #331 

## Next steps
- Get review and land https://github.com/elastic/elasticsearch/pull/131486
- Adapt Java/Ruby unit test cases to move to bridge changes

PLEASE IGNORE:
- `gradle.build` changes which are already counted in https://github.com/elastic/logstash-filter-elastic_integration/pull/330, this is a requirement to call Bridge Stable API interfaces.
-

### CODE REVIEW

File: src/main/java/co/elastic/logstash/filters/elasticintegration/PipelineConfigurationFactory.java [hunk 1]
```diff
@@ -47,8 +45,8 @@ public PipelineConfiguration parseNamedObject(final String json) throws Exceptio
         return configs.get(0);
     }
 
-    public PipelineConfiguration parseConfigOnly(final String pipelineId, final String jsonEncodedConfig) {
-        return new PipelineConfiguration(pipelineId, new BytesArray(jsonEncodedConfig), XContentType.JSON);
+    public PipelineConfigurationBridge parseConfigOnly(final String pipelineId, final String jsonEncodedConfig) {
+        return new PipelineConfigurationBridge(pipelineId, jsonEncodedConfig);
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/PipelineConfigurationFactory.java:49]: FYI: `XContentType.JSON` is moved to the bridge

File: src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java [hunk 2]
```diff
@@ -308,47 +276,8 @@ public synchronized EventProcessor build(final PluginContext pluginContext) {
...
-                @Override
-                @SuppressWarnings("unchecked")
-                public <T> List<T> loadExtensions(Class<T> extensionPointType) {
-                    if (extensionPointType.isAssignableFrom(PainlessExtension.class)) {
-                        final List<PainlessExtension> extensions = new ArrayList<>();
-
-                        extensions.add(new ConstantKeywordPainlessExtension()); // module: constant-keyword
-                        extensions.add(new ProcessorsWhitelistExtension());     // module: ingest-common
-                        extensions.add(new SpatialPainlessExtension());         // module: spatial
-                        extensions.add(new WildcardPainlessExtension());        // module: wildcard
```
[the remark this answers is not in the document]
Comment (yaauie) [reply src/main/java/co/elastic/logstash/filters/elasticintegration/EventProcessorBuilder.java:342]: It looks like we will need to find a way to apply https://github.com/elastic/logstash-filter-elastic_integration/pull/162 on the bridge-side in Elasticsearch.

File: src/main/java/co/elastic/logstash/filters/elasticintegration/IngestDuplexMarshaller.java [hunk 3]
```diff
@@ -323,14 +324,14 @@ private List<Object> internalize(final @Nonnull Collection<?> externalCollection
...
 
     /**
-     * Normalizes the IngestDocument's various metadata into a map that can be added to an Event
+     * Normalizes the IngestDocumentBridge's various metadata into a map that can be added to an Event
      *
      * @param ingestDocument the source
      * @return a simple map containing non-{@code null} metadata
      */
-    private Map<String,Object> normalizeIngestDocumentMetadata(final IngestDocument ingestDocument) {
+    private Map<String,Object> normalizeIngestDocumentMetadata(final IngestDocumentBridge ingestDocument) {
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/IngestDuplexMarshaller.java:332]: One interesting my found is, `ingestDocument.getIngestMetadata()` on line 342 throws exception because of `Map.copyOf()` which may happen if any of entry key or value is null. I have [directly send ingest metadata](https://github.com/mashhurs/elasticsearch/commit/78a3394b974aa3a5391894e33dc36d5aef788ad8) to plugin for debug purpose and caught it with below logs:
```
2025-07-15 18:12:10     with foreach processor
2025-07-15 18:12:10 [2025-07-16T01:12:10,284][INFO ][co.elastic.logstash.filters.elasticintegration.PreflightCheck] Connected to Elasticsearch version: 9.1.0-SNAPSHOT
2025-07-15 18:12:10 [2025-07-16T01:12:10,284][INFO ][co.elastic.logstash.filters.elasticintegration.PreflightCheck] Elasticsearch build_flavor: default
2025-07-15 18:12:10 [2025-07-16T01:12:10,367][INFO ][co.elastic.logstash.filters.elasticintegration.PreflightCheck] Elasticsearch license OK (active trial)
2025-07-15 18:12:10 [2025-07-16T01:12:10,379][INFO ][co.elastic.logstash.filters.elasticintegration.IngestDuplexMarshaller] collectedMetadata before:  {routing=null, version_type=null, index=integration-logstash_test.events-default, id=null, version=1}
2025-07-15 18:12:10 [2025-07-16T01:12:10,379][INFO ][co.elastic.logstash.filters.elasticintegration.IngestDuplexMarshaller] ingestDocument:  {_value=null, timestamp=2025-07-16T01:12:10.369038300Z}
2025-07-15 18:12:10 [2025-07-16T01:12:10,379][INFO ][co.elastic.logstash.filters.elasticintegration.IngestDuplexMarshaller] collectedMetadata after:  {routing=null, version_type=null, index=integration-logstash_test.events-default, id=null, version=1, timestamp=2025-07-16T01:12:10.369038300Z}
2025-07-15 18:12:10       iterates over the collection and proceeds the defined processor
```

File: build.gradle [hunk 4]
```diff
@@ -307,10 +307,6 @@ task shadeElasticsearchIngestGeoIpModule(type: com.github.jengelman.gradle.plugi
 
     mergeServiceFiles()
 
-    String shadeNamespace = "org.elasticsearch.ingest.geoip.shaded"
-    relocate('com.fasterxml.jackson', "${shadeNamespace}.com.fasterxml.jackson")
-    relocate('com.maxmind',           "${shadeNamespace}.com.maxmind")
```
Comment (mashhurs) [inline build.gradle:312]: We get "No X class found" exceptions if we relocate them and I am not seeing `org.elasticsearch.ingest.geoip.shaded.com.fasterxml.jackson.*` usages.

File: gradle.properties [hunk 5]
```diff
@@ -1,2 +1,3 @@
 LOGSTASH_PATH=../../logstash
-ELASTICSEARCH_TREEISH=main
+ELASTICSEARCH_REPO=mashhurs/elasticsearch
+ELASTICSEARCH_TREEISH=logstash-bridge-geoip-interfaces
```
Comment (mashhurs) [inline gradle.properties:3]: FYI: this will be removed once [upstream PR](https://github.com/elastic/elasticsearch/pull/132595) is merged.

File: src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/ValidatableIpDatabase.java [hunk 6]
```diff
@@ -1,13 +0,0 @@
...
- * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V.
- * under one or more contributor license agreements. Licensed under the
- * Elastic License 2.0; you may not use this file except in compliance
- * with the Elastic License 2.0.
- */
-package co.elastic.logstash.filters.elasticintegration.geoip;
-
-import org.elasticsearch.ingest.geoip.IpDatabase;
-
-public interface ValidatableIpDatabase extends IpDatabase {
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/geoip/ValidatableIpDatabase.java:11]: No direct usage.

File: src/main/java/co/elastic/logstash/filters/elasticintegration/ingest/RedactPlugin.java [hunk 7]
```diff
@@ -1,26 +0,0 @@
...
-
-import org.elasticsearch.ingest.Processor;
-import org.elasticsearch.plugins.IngestPlugin;
-import org.elasticsearch.license.XPackLicenseState;
-import org.elasticsearch.plugins.Plugin;
-import org.elasticsearch.xpack.redact.RedactProcessor;
-
-import java.util.Map;
-
-public class RedactPlugin extends Plugin implements IngestPlugin {
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/ingest/RedactPlugin.java:18]: moved to the upstream bridge.

File: src/main/java/co/elastic/logstash/filters/elasticintegration/util/PluginProjectResolver.java [hunk 8]
```diff
@@ -1,21 +0,0 @@
-package co.elastic.logstash.filters.elasticintegration.util;
-
-import org.elasticsearch.cluster.metadata.ProjectId;
-import org.elasticsearch.cluster.project.ProjectResolver;
-import org.elasticsearch.core.CheckedRunnable;
-
-public class PluginProjectResolver implements ProjectResolver {
```
Comment (mashhurs) [inline src/main/java/co/elastic/logstash/filters/elasticintegration/util/PluginProjectResolver.java:7]: Moved to the bridge, `ProjectIdResolverBridge` class.

**Review by yaauie — COMMENTED** [review]
Overall LGTM.

We need to first merge the upstream PR on elasticsearch https://github.com/elastic/elasticsearch/pull/132595#pullrequestreview-3137695264 and then ensure we're pointing at the correct `ELASTICSEARCH_REPO` and `ELASTICSEARCH_TREEISH` in `gradle.properties`.
